---
- name: Create image directory
  ansible.builtin.file:
    state: directory
    path: "{{ image_path }}"
    mode: "0700"

# Download cloud images
- name: Download cloud images
  ansible.builtin.get_url:
    url: "{{ item.image_url }}"
    dest: "{{ image_path }}/{{ item.cloud_image_file }}"
    mode: "0644"
    checksum: "{{ item.image_checksum }}"
  loop: "{{ os_images }}"
  when: 'item.state == "absent"'

# Delete cloud-init images, that are no longer needed
- name: Delete unused cloud-init images
  ansible.builtin.file:
    path: "{{ image_path }}{{ item.cloud_init_file }}"
    state: absent
  loop: "{{ os_images }}"
  when: 'item.state == "absent"'
