- hosts: localhost
  become: false
  gather_facts: false
  tasks:
    # Create variables files for images and VMs
    - name: Create Variable Files
      include_role:
        name: create_variables_file
      vars:
        variable_name: "{{ item }}"
      loop: "{{ variable_files }}"

- hosts: pvenodes
  become: true
  gather_facts: false

  tasks:
    - name: Download cloud image
      ansible.builtin.import_role:
        name: plano.proxmox.download_cloud_init_images
    - name: Create user files
      ansible.builtin.import_role:
        name: plano.proxmox.create_user_files

- hosts: pvenodes[0]
  become: false
  gather_facts: false

  tasks:
    - name: Create VMs
      ansible.builtin.import_role:
        name: plano.proxmox.create_vms
