---
# - name: Download cloud image for proxmox
#   hosts: proxmox
#   gather_facts: false

#   tasks:
#     - name: Download cloud image
#       ansible.builtin.import_role:
#         name: plano.proxmox.cloud_image
#       vars:
#         cloud_image_dest: /var/lib/vz/images/0

- name: Create VM on proxmox host
  hosts: proxmox
  gather_facts: false

  tasks:
    - name: Create VM
      ansible.builtin.import_role:
        name: plano.proxmox.create_vm
