---
- name: Disable swap
  ansible.builtin.command:
    cmd: swapoff -a
  become: true
  when: ansible_swaptotal_mb > 0

- name: Ensure swap is disabled in fstab
  ansible.builtin.lineinfile:
    path: /etc/fstab
    regexp: "^.*swap.*$"
    state: absent
  become: true

- name: Load necessary kernel modules
  ansible.builtin.copy:
    dest: /etc/modules-load.d/k8s.conf
    mode: "0644"
    content: |
      overlay
      br_netfilter
  become: true

- name: Apply sysctl settings
  ansible.builtin.copy:
    dest: /etc/sysctl.d/k8s.conf
    mode: "0644"
    content: |
      net.bridge.bridge-nf-call-iptables = 1
      net.bridge.bridge-nf-call-ip6tables = 1
      net.ipv4.ip_forward = 1
  become: true

- name: Reload sysctl settings
  ansible.builtin.command: sysctl --system
  become: true
