---
- name: Update repository cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Install python3-proxmoxer
  ansible.builtin.apt:
    name: python3-proxmoxer
    update_cache: true
    cache_valid_time: 3600
    state: present
